APT::FTPArchive::Release::Origin "Sirco";
APT::FTPArchive::Release::Label "Sirco";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 all";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Sirco APT Repo";
